export const START_CAROUSELL_LOAD = "START_CAROUSELL_LOAD";
export const CAROUSELL_LOADED = "CAROUSELL_LOADED";

export const LEFT_ARROW = "LEFT_ARROW";
export const RIGHT_ARROW = "RIGHT_ARROW";
export const ENTER_KEY = "ENTER_KEY";

export const CLICK_VIDEO = "CLICK_VIDEO";

export const CHANGE_VIEW = "CHANGE_VIEW";

export const GET_HISTORY = "GET_HISTORY";
export const START_GET_HISTORY = "START_GET_HISTORY";
export const POST_HISTORY = "POST_HISTORY";
export const RESET_POSITION = "RESET_POSITION";
